language: node_js

node_js:
  - "8"

services:
  - mongodb

addons:
  postgresql: "9.5"

install:
  - sudo apt-get install -y postgresql-9.5-postgis-2.3
  - sudo service postgresql restart
  - npm install coffeelint mocha coffeescript -g

before_script:
  - psql -c 'create database travis_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_postgis
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d travis_postgis
