language: node_js

node_js:
  - "lts/*"

addons:
  postgresql: "9.3"

services:
  - mongodb

before_script:
  - psql -c 'create database travis_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_postgis
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d travis_postgis
